### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by songxiansen521** [usgs/warc-iridium-sbd-decoder#1]
Hello,
    I am very glad to see that this project has helped me a lot.

   But when I downloaded the project, I reported an error with maven install; the prompt did not find some classes, such as MessageBuilder, Header BUilder, etc. Why?

   Thank you very much for helping me solve this problem.

   from chao

**Comment by mckelvym-usgs** [comment]
Hi Chao,

There are several factors that could be at play. Currently the project is being built with Java 8. If you have a different version of Java that may be the cause. 

Another cause could be running maven from one of the sub directories. Please run from the parent directory.

You can compare your build results to the latest build results: https://travis-ci.org/usgs/warc-iridium-sbd-decoder

For example, this build: https://travis-ci.org/usgs/warc-iridium-sbd-decoder/jobs/405922551

Thank you for reaching out.
