### ISSUE TITLE
MT SBD encoder

### ISSUE THREAD

**Issue by Providnuk** [usgs/warc-iridium-sbd-decoder#4]
Do you have any plans to implement encoder, to be able to send MT SBD Messages?

**Comment by mckelvym-usgs** [comment]
Not at present. Thanks for your inquiry.

**Comment by lromeraj** [comment]
> Do you have any plans to implement encoder, to be able to send MT SBD Messages?

@Providnuk I'm not sure if you're still interested in such a tool, but I've recently developed an Iridium SBD emulator that includes multiple tools for tasks like encoding, decoding, and transporting SBD messages. Take a look at the [following repository](https://github.com/lromeraj/isbd-emu), especially the [Sending a MT Message](https://github.com/lromeraj/isbd-emu#sending-a-mt-message) section in the README. I hope it is useful.
